import TanstackProvider from '@/config/providers/TanstackProvider'
import './globals.css'
import { openSans, tinos } from '@/utilities/fonts/fonts'
import MainNavigation from './components/ThisWebsiteOnly/Navigation/MainNavigation'
import Footer from './components/ThisWebsiteOnly/Footer/Footer'

export const metadata = {
  title: 'Kent Maintenance & Services',
  title: {
    default: `Kent Maintenance & Services`,
    template: `%s - Kent Maintenance & Services`,
  },
  // description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${openSans.className} ${tinos.variable} text-secondary`}
    >
      <body>
        <TanstackProvider>
          <MainNavigation />
          {children}
          <Footer />
        </TanstackProvider>
      </body>
    </html>
  )
}
