import React from 'react'
import Button from './components/Button'

export const metadata = {
  title: 'Kent Maintenance and Services',
  // description: 'Generated by create next app',
}

const Homepage = () => {
  return (
    <div>
      <div className="py-10 md:py-[80px] bg-gradient-to-br from-primary-400 to-primary">
        <div className={'container md:px-6 lg:px-10 xl:px-0'}>
          <h1
            className={
              'text-4xl md:text-[40px] font-bold text-white text-center font-tinos'
            }
          >
            Kent Maintenance & Services Limited
          </h1>
          <Button className="mx-auto mt-5" variant="light">
            One Call Does All
          </Button>
        </div>
      </div>
      <div className={'py-10 md:py-[80px]'}>
        <div
          className={
            'container md:px-6 lg:px-10 xl:px-0 grid grid-cols-1 md:grid-cols-2 gap-10'
          }
        >
          <div className="flex flex-col gap-2">
            <h3 className={'text-[22px] max-sm:leading-7 md:text-[26px] mb-4 font-semibold'}>
              Our local house cleaning services
            </h3>
            <p className={'text-paragraph'}>
              We are the premier provider of domestic & home cleaning throughout
              the UK. Specialising in providing unbeatable house cleaning, we
              have built an expertise for cleaning your home to the highest
              possible standard and supplying an exemplary customer service.
            </p>
            <p className={'text-paragraph'}>
              Our domestic cleaning service provides a fully vetted, reference
              checked and insured cleaner to your home that will deliver a
              professional clean to suit your individual needs.
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <h3 className={'text-[22px] max-sm:leading-7 md:text-[26px] mb-4 font-semibold'}>
              Our local house cleaning services
            </h3>
            <p className={'text-paragraph'}>
              Interested in becoming a franchisee? Find more information on our
              dedicated Maid2Clean Franchise website
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Homepage
